// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtjydquhteokujxhoypm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0anlkcXVodGVva3VqeGhveXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzM0OTAsImV4cCI6MjA2NjM0OTQ5MH0.7l92rTf-rCSeCFxlI1b_5ZTs0GPKeW1SyTOVwvzeh84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);